# Generated by Django 3.0.5 on 2021-07-23 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='None', max_length=30)),
                ('status', models.CharField(choices=[('default', 'default'), ('registered', 'registered'), ('in_work', 'in_work'), ('done', 'done')], default='default', max_length=20)),
                ('text', models.TextField(default=None)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Client')),
            ],
        ),
    ]
